name: device_info_plus_ohos
description: OpenHarmony implementation of the device_info_plus plugin.
version: 0.0.8
repository: https://github.com/harmonycandies/device_info_plus_ohos
topics:
  - device-info
  - device-info-plus
  - ohos
  - harmony-os
  - openharmony

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus_platform_interface: ^7.0.0
  flutter_lints: ^2.0.0
    
dev_dependencies:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      ohos:
        pluginClass: DeviceInfoPlusPlugin

 